apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
        octopusexport: OctopusExport
    spec:
      volumes:
        - name: mysql-sql
          configMap:
            name: mysql-sql
      containers:
        - name: mysql
          image: mysql
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: SolidUI@123
          volumeMounts:
            - name: mysql-sql
              mountPath: /docker-entrypoint-initdb.d/
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
