apiVersion: apps/v1
kind: Deployment
metadata:
  name: solidui-entrance
  labels:
    app: solidui-entrance
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: solidui-entrance
        octopusexport: OctopusExport
    spec:
      containers:
        - name: solidui-entrance
          image: '{{ .Values.image.hub }}/solidui-entrance:{{ .Values.image.tag }}'
          ports:
            - name: http
              containerPort: 12345
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
