# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: solidui
  name: {{ .Chart.Name }}-web
  labels:
    app: {{ .Chart.Name }}-web
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-web
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-web
    spec:
      containers:
        - name: {{ .Chart.Name }}-web
          image: '{{ .Values.image.hub }}/solidui-web:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8099
              protocol: TCP
          env:
            - name: TZ
              value: {{ .Values.timezone }}
          {{- if .Values.soliduiweb.resources }}
          resources:
            {{- toYaml .Values.soliduiweb.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.soliduiweb.readinessProbe.enabled }}
          readinessProbe:
            failureThreshold: {{ .Values.soliduiweb.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.soliduiweb.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.soliduiweb.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.soliduiweb.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.soliduiweb.readinessProbe.successThreshold }}
            httpGet:
              path: /
              port: http
              scheme: HTTP
          {{- end }}
          {{- if .Values.soliduiweb.livenessProbe.enabled }}
          livenessProbe:
            failureThreshold: {{ .Values.soliduiweb.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.soliduiweb.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.soliduiweb.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.soliduiweb.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.soliduiweb.livenessProbe.successThreshold }}
            httpGet:
              scheme: HTTP
              port: 8099
              path: /
          {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
